### ISSUE TITLE
我想引入这个js在我的某一篇文章里，我该怎么做？

### ISSUE THREAD

**Issue by asleep2** [HeyChioy/Typecho_CustomCssAndJs#1]
https://github.com/audiocogs/flac.js/releases

**Comment by kyuuseiryuu** [comment]
抱歉，本插件是引入全局 JS 和 CSS 的。如果你要在某篇文章里面单独引入一个 JS，你可以在文章中使用 script 标签。如：

```html
<script src="https://github.com/audiocogs/flac.js/releases/download/v0.2.1/flac.js"></script>
```

关于 script 标签的用法可以查阅 [script&gt;: The Script element - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Examples)
